ogcio/govie-ds

apps/docs/content/4-patterns/2-pages/2-service-unavailable.mdx
apps/docs/src/components/document/common/mdx.tsx
apps/docs/src/components/document/patterns/page-not-found.tsx
apps/docs/src/components/document/patterns/service-not-available.tsx

Addition of service unavailable component and usage of the component in pattern pages.

docs: add service-unavailable pattern

---

apps/docs/project.json

NX configuration name `production` is unresolved since the environment name is `prod`.
Accordingly with `getDeployEnvironment()` method in apps\docs package the right `DEPLOY_ENV` values must be:
* production
* staging
* uat
* development

ci: change nx configuration name for production

---

packages/html/ds/src/link/link.html
packages/html/ds/src/link/link.schema.ts
packages/html/ds/src/link/link.stories.ts
packages/html/ds/src/link/link.test.ts
packages/html/ds/styles.css

Revert dark mode changes on link component.
Storybook testing:

revert: dark mode on HTML link component

---

packages/html/storybook/.storybook/preview.tsx
packages/html/storybook/docs/introduction.mdx
packages/html/storybook/docs/precompiled.mdx

- Introduction and precompiled title updates.
- Copy code block content. Extra curly bracket removed which was resulting in an error during copy.
Storybook titles:
Example on Link component:

docs: update copy code block and meta tag

---

examples/wagtail/core/jinja/home_page.jinja
packages/html/ds/src/paragraph/paragraph.html
packages/html/ds/src/paragraph/paragraph.test.ts

- Enable html content with paragraph and associated tests.
- Example wagtail implementation with `govieLink` macro.

chore: enable html in paragraph

---

examples/vite/src/application.tsx
packages/react/ds/src/checkbox/checkbox.tsx
packages/react/ds/src/checkbox/checkboxes-group.tsx
packages/react/ds/src/error-text/error-text.stories.tsx
packages/react/ds/src/error-text/error-text.tsx
packages/react/ds/src/file-upload/file-upload.stories.tsx
packages/react/ds/src/file-upload/file-upload.tsx
packages/react/ds/src/hint-text/hint-text.stories.tsx
packages/react/ds/src/hint-text/hint-text.tsx
packages/react/ds/src/label/label.stories.tsx
packages/react/ds/src/label/label.tsx
packages/react/ds/src/select/select.stories.ts
packages/react/ds/src/select/select.tsx
packages/react/ds/src/text-input/text-input.stories.tsx
packages/react/ds/src/text-input/text-input.tsx
packages/react/ds/src/textarea/textarea.stories.tsx
packages/react/ds/src/textarea/textarea.tsx

As part of [21977](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/21977) I've refactored the `children` into a `text` prop so now it accepts `string` instead of a react node.

chore: refactor children prop

---

packages/react/ds/src/header/components/header-menu.tsx
packages/react/ds/src/header/components/header-search.tsx
packages/react/ds/src/header/header.tsx

Following a conversation with Ludwig and Andrea, a issue has come up in regards to using Server Actions in the Search component of the Header. Since react/types does not support that we have come up with a temporary workaround until React catches up

fix: add server action support

---

packages/html/ds/src/select/select.html
packages/react/ds/src/select/select.tsx

Minor fix to always match the `id` attr of the `select` with the `for` attr of the `label`

fix: match the id of select with for attr

---

examples/wagtail/core/jinja/vars.jinja
packages/html/ds/src/header/header.html

Seems that in Jinja, we can't access the array with the `.` dot notation.
Happened already with the tabs.

fix: html header in jinja

---

packages/html/ds/src/icon/icon.schema.ts
packages/react/ds/src/icon/icon.tsx

- Icon Id will accept other strings as well (if the user wishes to use a different icon set apart from the DS).
Testing on VS Code:

chore: expose icon type to accept string

---

package.json
packages/design/tailwind/css/components.css
packages/html/ds/src/button/button.stories.ts
packages/html/ds/src/checkbox/checkbox.html
packages/html/ds/src/checkbox/checkboxes-group.html
packages/html/ds/src/checkbox/checkboxes.schema.ts
packages/html/ds/src/checkbox/checkboxes.stories.ts
packages/html/ds/src/text-input/text-input.html
packages/html/ds/src/text-input/text-input.schema.ts
packages/html/ds/src/text-input/text-input.stories.ts
packages/html/ds/src/textarea/textarea.html
packages/html/ds/src/textarea/textarea.schema.ts
packages/html/ds/src/textarea/textarea.stories.ts
packages/html/storybook/.storybook/main.ts
packages/react/ds/src/button/button.stories.tsx
packages/react/ds/src/button/button.tsx
packages/react/ds/src/button/types.ts
packages/react/ds/src/checkbox/checkbox.stories.tsx
packages/react/ds/src/checkbox/checkbox.tsx
packages/react/ds/src/checkbox/checkboxes-group.tsx
packages/react/ds/src/text-input/text-input.stories.tsx
packages/react/ds/src/textarea/textarea.stories.tsx
packages/react/storybook/.storybook/main.ts
pnpm-lock.yaml

- Added pseudo-states plugin to have control of focus and hover in storybook 
- Added disable style for input, text area and checkbox item
- Added hover state for checkbox

chore: Adding pseudo button states in storybook for testing

---

apps/docs/content/3-components/2-library/32-radio-button.mdx
apps/docs/dictionary.txt
apps/docs/src/components/form/radio.tsx
examples/nextjs/src/app/page.tsx
examples/vite/src/application.tsx
examples/wagtail/core/jinja/home_page.jinja
examples/wagtail/core/jinja/vars.jinja
packages/html/ds/src/radio/radio-group.stories.ts
packages/html/ds/src/radio/radio.html
packages/html/ds/src/radio/radio.schema.ts
packages/html/ds/src/radio/radio.stories.ts
packages/html/ds/src/radio/radio.test.ts
packages/html/ds/src/radio/radio.ts
packages/html/ds/src/radio/radios-group.html
packages/react/ds/src/index.ts
packages/react/ds/src/radio/radio-group.stories.tsx
packages/react/ds/src/radio/radio.stories.tsx
packages/react/ds/src/radio/radio.test.tsx
packages/react/ds/src/radio/radio.tsx
packages/react/ds/src/radio/radios-group.tsx
packages/react/ds/src/radio/types.ts
packages/react/storybook/.storybook/preview.tsx

Implementation of the following:
- Expose the `Radio` Component
- Add the following props:
1.   `checked` -> if `true` the input is checked by default
2.  `onChange` --> callback function
- Rename the prop `fieldId` to `groupId`
- Add stories for the `Radio` Component
The above applies to the Macro and React libraries
**SB screenshots**
1d33f26)

fix: radio feedback fixes

---

apps/docs/content/3-components/2-library/pagination.mdx
apps/docs/dictionary.txt
packages/design/tailwind/css/components.css
packages/html/ds/src/button/button.html
packages/html/ds/src/pagination/pagination.html
packages/react/ds/src/pagination/pagination.tsx

- Pagination (react and html): usage icon classes on next and previous buttons if no label is shown (e.g. under 640px - small screens).
- Extended class names on button macro.
- Documentation update.
Testing:

fix: pagination consistent width across html and react platforms

---

apps/docs/package.json

change the order of the scripts that run in the `build` process so that it copies the styles for macros and then create the optimized build

fix: change order of scripts

---

apps/docs/content/3-components/2-library/tooltip.mdx
apps/docs/dictionary.txt
apps/docs/src/components/document/common/mdx.tsx
packages/design/tailwind/css/components.css
packages/react/ds/src/index.ts
packages/react/ds/src/tooltip/tooltip.stories.tsx
packages/react/ds/src/tooltip/tooltip.test.tsx
packages/react/ds/src/tooltip/tooltip.tsx

- Addition of react tooltip component.
- Unit tests.
- Documentation update.
- Storybook update.
- 4 variants, top, bottom, left and right.
Storybook testing:

feat: add react tooltip component

---

apps/docs/content/3-components/2-library/tooltip.mdx
examples/wagtail/core/jinja/home_page.jinja
packages/design/tailwind/css/components.css
packages/html/ds/src/common/instances.ts
packages/html/ds/src/index.ts
packages/html/ds/src/tooltip/tooltip.html
packages/html/ds/src/tooltip/tooltip.schema.ts
packages/html/ds/src/tooltip/tooltip.stories.ts
packages/html/ds/src/tooltip/tooltip.test.ts
packages/html/ds/src/tooltip/tooltip.ts
packages/html/storybook/.storybook/preview.tsx
packages/react/ds/src/tooltip/tooltip.stories.tsx

Addition of:
- Tooltip HTML and jinja macro.
- Documentation update.
- Testing.
- Example page update.
- Tooltip instance initialised.
- Root level decorator for tooltip.
Documentation site:

feat: add html and macro for tooltip

---

packages/react/ds/src/summary-list/summary-list.tsx

Testing done locally on storybook:

docs: update summary list row display name on storybook

---

packages/html/ds/src/common/aria-attributes.html
packages/html/ds/src/link/link.html
packages/html/macro/src/macro.ts

- The built-in `items()` function is not being currently read by the python environment, so ended up by creating a custom `items` pipe.
- Without `items` pipe, Jinja tries to unpack the keys of the dictionary into key, value, which leads to the error.

fix: update common aria attributes

---

packages/design/tailwind/css/components.css
packages/html/ds/src/tooltip/tooltip.stories.ts
packages/html/ds/src/tooltip/tooltip.test.ts
packages/html/ds/src/tooltip/tooltip.ts
packages/react/ds/src/tooltip/tooltip.stories.tsx
packages/react/ds/src/tooltip/tooltip.test.tsx
packages/react/ds/src/tooltip/tooltip.tsx

Tooltip updated with:
- Visibility on focus.
- Hide on escape key.
- Max characters to 100.
- Max width to 300px.

fix: update tooltip with escape and focus functionality

---

examples/vite/src/application.tsx

Example vite app was throwing an error on incorrect Toast import. Now fixed in this PR.

chore: update example vite app with correct usage of toast

---

packages/html/ds/src/button/button-schema.ts
packages/html/ds/src/button/button.html
packages/html/ds/src/button/button.test.ts
packages/html/ds/src/pagination/pagination.html
packages/react/ds/src/button/button.test.tsx
packages/react/ds/src/button/button.tsx
packages/react/ds/src/button/types.ts

Previously I didn't touched button since it could've caused regression. Now exposing button data test id separately.

chore: update data test id for button

---

packages/react/ds/src/tabs/tab-list.tsx
packages/react/ds/src/tabs/tabs.stories.tsx
packages/react/ds/src/tabs/tabs.test.tsx

- Update initial set active tab if any children got `checked` true.
- If no `checked` state is defined then set `0` index tab item to be visible.
- Added associated story for that.
- Added associated unit test.
Testing Screenshot:

fix: update tab list checked state

---

packages/html/ds/src/helpers/buttons.tsx
packages/react/ds/src/icon-button/icon-button.test.tsx
packages/react/ds/src/icon-button/icon-button.tsx

Icon button with medium size was showing small icon

fix: icon button sizes

---

apps/docs/src/app/page.tsx

- Remove phase banner from docs
[27763](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/27763)

docs: removing phase banner from docs

---

packages/design/tailwind/css/components/text-area.css
packages/react/ds/src/textarea/textarea.stories.tsx
packages/react/ds/src/textarea/textarea.tsx

Adding clearButtonEnabled on TextArea component

fix: optional clearButtonEnabled on TextArea component

---

apps/docs/content/4-patterns/2-pages/6-loading.mdx
apps/docs/src/app/[...slug]/page.tsx
apps/docs/src/components/document/common/mdx.tsx
apps/docs/src/components/document/patterns/loading.tsx

Addition of loading pattern.
N/A.
Feedback form and the mdx code were too close to each-other so added a gap between them.

docs: add loading pattern

---

packages/html/ds/src/helpers/forms.tsx
packages/html/ds/src/select/select.stories.ts
packages/html/ds/src/select/types.ts
packages/react/ds/src/select/select.stories.tsx

Update select option with placeholder text on React and HTML lib.
N/A.
N/A.

fix: add placeholder option on select

---

packages/react/ds/src/button-group/button-group.test.tsx
packages/react/ds/src/button-group/button-group.tsx
packages/react/ds/src/hooks/use-dom-id.ts

When a `ButtonGroupItem` component is placed inside a `<form>` element, clicking it triggers the form submission. This behavior occurs because the rendered button defaults to `type="submit"`.

fix: add button type to button group item

---

apps/docs/src/components/document/components/component-status-table.tsx
apps/docs/src/lib/helper.ts
packages/html/ds/src/file-upload/file-upload.stories.ts

- The old structure file structure follows `getComponents` schema which is dependant on file names.
- The new structure now have `react.mdx`, `html.mdx` and `design.mdx` files.
Instead of refactoring `getComponents` component to accept 2 formats which is being used on many places e.g. `storybook-frame.tsx` and others. I created a **temporary** file `helper.ts` which exports `getComponentsTemp` to be used on component status table. This will be removed later once we have all the components following the consistent pattern.  
N/A.
N/A.

docs: add temporary helper for new folder structure

---

apps/docs/src/lib/theme-utils.ts

On production build, the theme builder preview is not updating the content.
It looks like the document.styleSheets is not returning the `:root` element.

fix: theme builder

---

apps/docs/src/components/document/resources/copy-to-clipboard-button.tsx
apps/docs/src/components/document/resources/download-icon-button.tsx
apps/docs/src/components/document/resources/download-svg.tsx
apps/docs/src/components/document/resources/logos.tsx

Add download svg icon button along with copy to clipboard.
N/A.
N/A.

docs: download svg icon button

---

apps/docs/content/3-components/2-library/combo-box.mdx
packages/design/tailwind/css/components/combo-box.css
packages/html/ds/src/helpers/combobox.ts
packages/react/ds/src/combo-box/dropdown-item.tsx

- Removed duplicate `gi-combobox-toggle`.
- Add `gi-combobox-dropdown-item` class that deals separately with border top and bottom.
- Removed unnecessary border bottom classes that were conflicting with the focus state of native button.
N/A.
N/A.

fix: update combo box focus state

---

packages/react/ds/src/input-password/input-password.test.tsx
packages/react/ds/src/input-password/input-password.tsx

- Update input password react component with forward ref prop.
N/A.
N/A.

fix: add forward ref to input password

---

examples/nextjs/src/app/page.tsx
packages/react/ds/src/button-group/button-group.stories.tsx
packages/react/ds/src/button-group/button-group.test.tsx
packages/react/ds/src/button-group/button-group.tsx
packages/react/ds/src/input-checkbox-group/input-checkbox-group.stories.tsx
packages/react/ds/src/input-checkbox-group/input-checkbox-group.tsx
packages/react/ds/src/input-checkbox-group/types.ts
packages/react/ds/src/input-radio-group/input-radio-group.stories.tsx
packages/react/ds/src/input-radio-group/input-radio-group.tsx
packages/react/ds/src/input-radio-group/types.ts
packages/react/ds/src/input-radio/input-radio.tsx
packages/react/ds/src/select/select-next.stories.tsx
packages/react/ds/src/select/select-next.tsx
packages/react/ds/src/select/types.ts
packages/react/ds/src/textarea/textarea.stories.tsx
packages/react/ds/src/textarea/textarea.tsx

- Update `InputCheckbox`, `InputRadio`, `TextArea`, `SelectNext`, and `ButtonGroup` with `value` props since our components offer controlled inputs.
- Update examples page with RHF (React Hook Form).
N/A.
N/A.

fix: update InputRadio, InputCheckbox, SelectNext and TextArea with controlled props

---

packages/design/tailwind/css/components/card.css

Due to recent changes on tanstack grid, `gi-table` was updated and it caused the `gi-card-image` with unintentional changes. Removed `gi-table` in this PR.
NA.
NA.

fix: remove table styling from card image

---

apps/docs/content/3-components/2-library/input-text/react.mdx
apps/docs/dictionary.txt
packages/react/ds/src/input-text/input-text.stories.tsx
packages/react/ds/src/input-text/input-text.tsx
packages/react/ds/src/input-text/type.ts

- Add `ReactNode` type to `iconStart` and `iconEnd`.
- Example: Add spinner or other svg component.
N/A.
N/A.

fix: update input text component to accept react node for icon start/end

---

apps/docs/content/3-components/2-library/header/react.mdx
packages/html/ds/src/helpers/breadcrumbs.ts
packages/html/ds/src/helpers/list.ts
packages/react/ds/src/header/header.stories.tsx
packages/react/ds/src/header/header.tsx
packages/react/ds/src/header/types.ts
packages/react/ds/src/i18n/translations/en.json

- Add a boolean flag to hide/show menu label on header.
N/A.
N/A.

fix: toggle menu label visibility
