apps/docs/content/4-patterns/0-index.mdx, apps/docs/content/4-patterns/1-ask-users-for/1-addresses.mdx, apps/docs/content/4-patterns/2-pages/1-page-not-found.mdx, apps/docs/content/4-patterns/2-pages/2-service-unavailable.mdx
=> docs: update pattern's status

apps/docs/content/4-patterns/1-ask-users-for/2-contact-dept-or-service.mdx, apps/docs/src/components/document/common/mdx.tsx, apps/docs/src/components/document/patterns/contact-dept-or-service.tsx
- Addition of contact department or service pattern using existing react components.
=> docs: add contact department pattern

apps/docs/src/app/contact/page.tsx
=> docs: add link to contact page

.github/workflows/ci.yml, .github/workflows/deploy-docs-prod.yml, apps/docs/project.json, apps/docs/src/lib/config.ts, package.json
Addition of `uat` and `staging` environments.
=> ci: add uat and staging environments

apps/docs/content/2-foundations/2-design-tokens/1-overview.mdx, apps/docs/dictionary.txt
- Content added for design token overview and benefits.
=> docs: update design token content

.github/workflows/deploy-html-storybook-prod.yml
This may resolve the following error on html storybook deployment:
https://github.com/ogcio/govie-ds/actions/runs/10681980094
=> ci: install nx html storybook

examples/wagtail/core/jinja/home_page.jinja, packages/html/storybook/.storybook/main.ts, packages/html/storybook/.storybook/preview.tsx, packages/html/storybook/static/macros/footer/footer.html, packages/html/storybook/static/macros/footer/helpers.html, packages/html/storybook/static/macros/header/header.html, packages/html/storybook/static/macros/heading/heading.html, packages/html/storybook/static/macros/link/link.html, packages/html/storybook/static/macros/paragraph/paragraph.html
Changed the path so that it matches the path complied in `storybook-static` folder therefore finding the templates on import.
=> fix: add templates as static for storybook prod build

packages/html/ds/src/header/components/headerDesktop.html, packages/html/ds/src/header/components/headerSmall.html
Fix to stop the focus state from adding `1px`
=> fix: html checkbox component

apps/docs/content/3-components/2-library/29-phase-banner.mdx, apps/docs/src/lib/components.ts, packages/html/ds/src/phase-banner/phase-banner.html, packages/html/ds/src/phase-banner/phase-banner.schema.ts, packages/html/ds/src/phase-banner/phase-banner.stories.ts, packages/html/ds/src/phase-banner/phase-banner.test.ts, packages/react/ds/src/phase-banner/phase-banner.tsx
- Fix text colour 
- Add HTML implementation
=> fix: phase banner component

apps/docs/src/lib/components.ts, packages/html/ds/src/hint-text/hint-text.html, packages/html/ds/src/label/label.html, packages/html/ds/src/text-input/text-input.html, packages/html/ds/src/text-input/text-input.stories.ts, packages/react/ds/src/form-group/form-group.tsx, packages/react/ds/src/hint-text/hint-text.tsx, packages/react/ds/src/label/label.tsx, packages/react/ds/src/text-input/text-input.tsx
- Fixes to html and react text-input component after design feedback.
- Addition of new stories to html text-input.
=> chore: update html and react text-input component styling  

apps/docs/content/3-components/2-library/41-textarea.mdx, apps/docs/src/lib/components.ts, packages/react/ds/src/index.ts, packages/react/ds/src/label/label.tsx, packages/react/ds/src/textarea/textarea.stories.tsx, packages/react/ds/src/textarea/textarea.tsx
Testing on Storybook:
Doc site:
=> feat: add react textarea component

.github/workflows/chromatic.yml, .github/workflows/ci.yml, .github/workflows/release-please.yml, .release-please-manifest.json, apps/docs/project.json, packages/build/eslint-config/project.json, packages/build/prettier-config/project.json, packages/design/deepmerge/project.json, packages/design/tailwind/project.json, packages/html/ds/project.json, packages/react/ds/project.json, packages/themes/govie/project.json, release-please-config.json, tokens/project.json
* Add release please workflow
* Chromatic workflow will run only on release please branch
=> ci: add release please

apps/docs/content/3-components/2-library/22-link.mdx, apps/docs/package.json, apps/docs/src/components/document/common/mdx.tsx, apps/docs/src/lib/components.ts, examples/nextjs/package.json, examples/vite/package.json, examples/vite/src/application.tsx, packages/build/prettier-config/prettierrc.json, packages/design/tailwind/css/components.css, packages/design/tailwind/css/layout.css, packages/design/tailwind/package.json, packages/design/tailwind/src/create-theme.ts, packages/html/ds/package.json, packages/html/ds/src/link/link.html, packages/html/ds/src/link/link.schema.ts, packages/html/ds/src/link/link.stories.ts, packages/html/ds/src/link/link.test.ts, packages/html/ds/styles.css, packages/html/ds/tailwind.config.ts, packages/html/storybook/package.json, packages/react/ds/package.json, packages/react/ds/src/link/link.tsx, packages/react/ds/src/tabs/tab-item.tsx, packages/react/ds/src/tabs/tab-list.tsx, packages/react/ds/src/tabs/tabs.tsx, packages/react/ds/styles.css, packages/react/ds/tailwind.config.ts, packages/react/storybook/package.json, pnpm-lock.yaml
=> fix: improve link doc with tabs

apps/docs/src/lib/components.ts, examples/wagtail/core/jinja/home_page.jinja, packages/html/ds/src/common/render.ts, packages/html/ds/src/file-upload/file-upload.html, packages/html/ds/src/file-upload/file-upload.schema.ts, packages/html/ds/src/file-upload/file-upload.stories.ts, packages/html/ds/src/file-upload/file-upload.test.ts, packages/react/ds/src/file-upload/file-upload.stories.tsx
Addition of:
- HTML file upload component.
- Update jinja macros with usage of file upload component.
Storybook testing:
=> feat: add html file-upload component

packages/html/ds/src/file-upload/file-upload.schema.ts
Fixes build errors on `packages/html/ds`.
=> chore: update schema description

.github/workflows/release-please.yml, apps/docs/content/3-components/2-library/28-paragraph.mdx, packages/design/tailwind/css/typography.css, packages/design/tailwind/src/create-theme.ts, packages/html/ds/src/paragraph/paragraph.html, packages/html/ds/src/paragraph/paragraph.test.ts, packages/react/ds/src/paragraph/paragraph.tsx
* use design tokens for heading and paragraph
=> fix: typography

examples/wagtail/core/jinja/vars.jinja, packages/design/tailwind/css/typography.css, packages/html/ds/src/header/components/headerDesktop.html, packages/html/ds/src/header/components/headerSmall.html, packages/html/ds/src/header/header.schema.ts, packages/html/ds/src/header/header.stories.ts, packages/html/ds/src/header/header.test.ts, packages/react/ds/src/header/header.stories.tsx, packages/react/ds/src/header/header.tsx
* update HTML schema to match React
* set label for tools optional
* set logo href optional
* review font for title
=> fix: header improvements

packages/design/tailwind/css/typography.css, packages/design/tailwind/src/create-theme.ts, packages/html/ds/src/header/components/headerMenu.html, packages/react/ds/src/header/components/header-menu.tsx, packages/react/ds/src/header/header.tsx
* restore default in theme
* fix header drawer
=> fix: review header

packages/html/ds/src/button/button-schema.ts, packages/html/ds/src/button/button.html, packages/html/ds/src/button/button.stories.ts, packages/react/ds/src/button/button.stories.tsx, packages/react/ds/src/button/button.tsx, packages/react/ds/src/button/types.ts
- Add `className` to prop to Button component in order to give the users the flexibility to style the component
=> fix: icon button

packages/html/ds/src/button/button-schema.ts, packages/html/ds/src/button/button.html, packages/html/ds/src/button/button.stories.ts, packages/react/ds/src/button/button.stories.tsx, packages/react/ds/src/button/button.tsx, packages/react/ds/src/button/types.ts
- Remove the `className` prop
- Remove the Icon button story as a new component will be implemented for that use case
=> fix: remove classname and icon button from component

apps/docs/content/3-components/2-library/32-radio-button.mdx, apps/docs/src/components/form/radio.tsx
PR to adjust the id's of the radio as they had matching id's and that was leading to unexpected results
Thanks @ramonmulia for spotting
=> fix: radio id on docs

apps/docs/content/3-components/2-library/17-header.mdx, apps/docs/content/4-patterns/2-pages/1-basic-page.mdx, packages/design/tailwind/css/components.css, packages/design/tailwind/css/typography.css, packages/html/ds/src/button/button.stories.ts, packages/html/ds/src/file-upload/file-upload.html, packages/html/ds/src/header/components/headerMenu.html, packages/html/ds/src/select/select.html, packages/html/ds/src/text-input/text-input.html, packages/react/ds/src/button/button.stories.tsx, packages/react/ds/src/checkbox/checkbox.tsx, packages/react/ds/src/file-upload/file-upload.tsx, packages/react/ds/src/header/components/header-menu.tsx, packages/react/ds/src/select/select.tsx, packages/react/ds/src/text-input/text-input.tsx
=> feat: adding focus state

apps/docs/content/3-components/2-library/22-icon.mdx, apps/docs/content/5-resources/5-icons.mdx, apps/docs/src/components/document/common/mdx.tsx, apps/docs/src/components/document/resources/icon-grid-layout.tsx, packages/html/ds/src/icon/icon.html
- Addition of icon resource page.
- Showcase of icons.
=> docs: add icon resource page

apps/docs/content/3-components/2-library/10-checkbox.mdx, apps/docs/content/3-components/2-library/17-file-upload.mdx, apps/docs/content/3-components/2-library/22-icon-button.mdx, apps/docs/content/3-components/2-library/24-label.mdx, apps/docs/content/3-components/2-library/25-link.mdx, apps/docs/content/3-components/2-library/35-section-break.mdx, apps/docs/content/3-components/2-library/36-select.mdx, apps/docs/content/3-components/2-library/43-text-input.mdx, apps/docs/dictionary.txt, apps/docs/src/components/document/common/mdx.tsx, apps/docs/src/lib/components.ts, packages/html/ds/src/label/label.stories.ts, packages/react/ds/src/checkbox/checkbox.stories.tsx, packages/react/ds/src/checkbox/checkboxes-group.tsx, packages/react/ds/src/checkbox/checkboxes.test.tsx, packages/react/ds/src/index.ts, packages/react/ds/src/test-utils.ts, packages/react/ds/src/text-input/text-input.test.tsx, packages/react/ds/src/textarea/textarea.test.tsx
Update component guidelines for: 
- Icon button.
- File upload.
- Checkbox.
- Label.
- Link.
- Section break.
- Select.
- Text input.
Additionally:
- Minor fixes to exports.
- Links update.
=> docs: update component usage guideline

packages/html/ds/src/header/components/headerMenu.html, packages/react/ds/src/header/components/header-menu.tsx
PR to fix an issue with the header, the page has a slight y scroll when it's not neccessary
=> fix: height overflows on header

packages/design/tailwind/css/components.css, packages/design/tailwind/css/typography.css, packages/html/ds/src/paragraph/paragraph.stories.ts, packages/html/ds/src/tag/tag.stories.ts
- removed margins from components ( with the exception of `SectionBreak` )
- added macro fixes for tag and paragraph ( include `path` )
=> feat: remove margins

examples/wagtail/core/jinja/home_page.jinja, packages/html/ds/src/pagination/pagination.html, packages/html/macro/src/macro.ts
- Replaced the `push` method with `append`. 
- Used a `temp` variable to mutate the array as the `append` method works in place and it would have return a `None` value
=> fix: replace push method with append

apps/docs/public/templates/search-page.html, packages/html/ds/src/header/components/headerSearchContainer.html, packages/react/ds/src/header/components/header-search.tsx
- fixed the import for js asset
- removed margin for iconButton on Header Search
=> fix: js import search template

apps/docs/content/3-components/2-library/breadcrumbs.mdx
=> docs: add breadcrumbs link

apps/docs/content/3-components/2-library/table.mdx, apps/docs/dictionary.txt, apps/docs/src/components/document/common/mdx.tsx, examples/wagtail/core/jinja/home_page.jinja, packages/design/tailwind/css/components.css, packages/html/ds/src/table/table.html, packages/html/ds/src/table/table.schema.ts, packages/html/ds/src/table/table.stories.ts, packages/html/ds/src/table/table.test.ts, packages/react/ds/src/index.ts, packages/react/ds/src/table/caption.tsx, packages/react/ds/src/table/table.stories.tsx
- Add HTML and macro component for table.
- Expose associated components for documentation.
- Documentation and example jinja page update.
Testing:
=> feat: table component html and macro implementation

packages/react/ds/src/index.ts, packages/react/ds/src/select-composable/select.stories.tsx, packages/react/ds/src/select-composable/select.test.tsx, packages/react/ds/src/select-composable/select.tsx, packages/react/ds/src/select/select.stories.ts, packages/react/ds/src/select/select.tsx
PR to create and implement the composable version of the `Select` component.
SB screenshots:
=> feat: select composable

packages/design/tailwind/css/components.css
=> fix: update radio min width and height

packages/design/tailwind/css/components.css, packages/html/ds/src/header/header.html, packages/html/ds/src/header/header.schema.ts, packages/html/ds/src/header/header.stories.ts, packages/react/ds/src/header/header.stories.tsx, packages/react/ds/src/header/header.tsx, packages/react/ds/src/header/types.ts
- reactjs updated
- macro updated
=> fix: Header "order" items for accessbility and Adding "showTitleOnMobile" prop in Header

packages/design/tailwind/css/components.css, packages/html/ds/src/text-input/text-input.html, packages/html/ds/src/text-input/text-input.schema.ts, packages/html/ds/src/text-input/text-input.stories.ts, packages/html/ds/src/text-input/text-input.test.ts, packages/html/ds/src/textarea/textarea.html, packages/react/ds/src/text-input/text-input.stories.tsx, packages/react/ds/src/text-input/text-input.test.tsx, packages/react/ds/src/text-input/text-input.tsx, packages/react/ds/src/textarea/textarea.stories.tsx, packages/react/ds/src/textarea/textarea.tsx
- removed all width constraints of the components
- added storybook examples for maxLength, custom width, responsive
- reactjs and macro updated
=> fix: fixes for textarea and input

packages/design/tailwind/css/components.css
Reviews mentioned here: https://www.chromatic.com/test?appId=66d71adc83425e26c052e5e2&id=67a361f5c206363b20984ba0
=> chore: update tooltip with design feedback

apps/docs/content/3-components/2-library/accordion.mdx, examples/wagtail/core/jinja/home_page.jinja, packages/html/ds/src/accordion/accordion.html
- macro updated
- docs updated
- wagtail example added
=> fix: Updating accordion docs and macro fixes

packages/design/tailwind/css/typography.css, packages/react/ds/src/link/link.tsx
Fix the border visibility using `display: inline-block` for the links
=> fix: link focus state

packages/react/ds/package.json, packages/react/ds/percy.yaml, pnpm-lock.yaml
Percy is helpful for cross-browser snapshot testing with different form factors.
=> chore: add percy integration

apps/docs/public/templates/layout-page.html, apps/docs/src/components/document/grid/grid-primitives.tsx
Minor changes to the UI which was breaking on the layout pattern example.
N/A.
N/A.
=> docs: update layout page banner image

packages/html/ds/tailwind.config.ts, packages/react/ds/tailwind.config.ts
Added `gi-h-screen` and `gi-w-full` to safe-list so that it doesn't get purged by the tailwind processor.
N/A.
N/A.
=> fix: update tailwind config safelist

apps/docs/.env.production
[26747](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/26747)
- Link updated in PROD env.
=> chore: updating form link

apps/docs/content/3-components/2-library/alert.mdx, apps/docs/content/3-components/2-library/breadcrumbs.mdx, apps/docs/content/3-components/2-library/button.mdx, apps/docs/content/3-components/2-library/card.mdx, apps/docs/content/3-components/2-library/checkbox.mdx, apps/docs/content/3-components/2-library/combo-box.mdx, apps/docs/content/3-components/2-library/file-upload.mdx, apps/docs/content/3-components/2-library/footer.mdx, apps/docs/content/3-components/2-library/header.mdx, apps/docs/content/3-components/2-library/icon-button.mdx, apps/docs/content/3-components/2-library/input-password.mdx, apps/docs/content/3-components/2-library/link.mdx, apps/docs/content/3-components/2-library/modal.mdx, apps/docs/content/3-components/2-library/phase-banner.mdx, apps/docs/content/3-components/2-library/progress-stepper.mdx, apps/docs/content/3-components/2-library/radio-button.mdx, apps/docs/content/3-components/2-library/select.mdx, apps/docs/content/3-components/2-library/stack.mdx, apps/docs/content/3-components/2-library/text-input.mdx, apps/docs/content/3-components/2-library/textarea.mdx, apps/docs/content/3-components/2-library/toast.mdx
Update status and links for each component in documentation website
=> docs: update status and link

apps/docs/content/3-components/2-library/footer.mdx, packages/design/tailwind/css/components/footer.css, packages/react/ds/src/footer/footer.stories.tsx, packages/react/ds/src/footer/footer.tsx, packages/react/ds/src/input-password/input-password.stories.tsx, packages/react/ds/src/stack/stack.tsx, packages/react/ds/src/text-input/text-input.stories.tsx, packages/react/ds/src/textarea/textarea.stories.tsx
Improve Footer example using Stack and not div with Tailwind classes
=> fix: use stack in footer

apps/docs/content/3-components/2-library/drawer.mdx, packages/design/tailwind/css/components/drawer.css, packages/design/tailwind/css/components/modal.css, packages/html/ds/src/helpers/modal.tsx, packages/react/ds/src/drawer/drawer.stories.tsx, packages/react/ds/src/drawer/drawer.tsx, packages/react/ds/src/modal/modal.tsx
Fixes for Drawer component width
[27208](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/27208)
=> fix: Drawer component width size

packages/html/ds/src/header/header.stories.ts, packages/html/ds/src/header/header.ts, packages/html/ds/src/helpers/modal.tsx, packages/html/ds/src/modal/modal.stories.ts
Header and Modal were missing some css.
=> fix: html header and modal

apps/docs/content/3-components/2-library/button.mdx, apps/docs/src/components/document/common/mdx.tsx, packages/design/tailwind/css/components/button.css, packages/html/ds/src/button/button-group/button-group.stories.ts, packages/html/ds/src/button/button.stories.ts, packages/react/ds/src/button/button-group/button-group.stories.tsx, packages/react/ds/src/button/button-group/button-group.tsx, packages/react/ds/src/button/button.stories.tsx, packages/react/ds/src/index.ts
- Add react button group component.
- Add html button group implementation.
- Associated docs update.
N/A.
N/A.
=> feat: add button group component

packages/react/ds/src/header/header.tsx
[27898](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/27898)
=> fix: Fix secondaryLink "key" lint error

examples/vite/src/application.tsx, packages/react/ds/src/forms/form-field-with-tag/form-field-with-tag.tsx, packages/react/ds/src/i18n/translations/en.json, packages/react/ds/src/index.ts
Implementation of a non exposed component of form field with tag.
N/A.
N/A.
=> fix: add form field with tag component

packages/design/tailwind/css/components/input-checkbox.css
Label width adjusted.
N/A.
N/A.
=> fix: update checkbox label width

packages/design/tailwind/css/components/common.css, packages/design/tailwind/css/components/footer.css, packages/design/tailwind/css/components/header.css, packages/design/theme-builder/src/validation/schema/brand/brand-schema.ts, packages/design/theme-builder/src/validation/schema/semantic/color-schema.ts, packages/html/ds/src/footer/footer.stories.ts, packages/html/ds/src/header/header.stories.ts, packages/react/ds/src/drawer/drawer.stories.tsx, packages/react/ds/src/drawer/drawer.tsx, packages/react/ds/src/footer/footer.stories.tsx, packages/react/ds/src/footer/footer.tsx, packages/react/ds/src/header/components/header-slot.tsx, packages/themes/doete/tokens/light/brand/brand.json, packages/themes/doete/tokens/light/semantic/color.json, tokens/tokens/light/brand/brand.json, tokens/tokens/light/semantic/color.json
Adding new semantic colors + header/footer changes
[27977](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/27977)
=> feat: updated semantic colors + header/footer changes

apps/docs/content/3-components/2-library/side-nav.mdx, apps/docs/src/components/navigation/side-navigation-connected.tsx, apps/docs/src/components/navigation/side-navigation.tsx, apps/docs/src/components/navigation/use-side-navigation-items.tsx, packages/design/tailwind/css/components/side-nav.css, packages/html/ds/src/side-nav/side-nav.stories.ts, packages/html/ds/src/side-nav/types.ts, packages/react/ds/src/side-nav/side-nav.stories.tsx, packages/react/ds/src/side-nav/side-nav.tsx, packages/react/ds/src/side-nav/types.ts
- Updated `parent` prop with `primary`.
- New prop as `secondary` to distinguish child elements with parent.
- Optimised `SideNav` and `SideNavItem` react component.
- Updated associated docs.
- Usage of `SideNav` on doc site.
- Fixed icon padding and border padding issue.
N/A.
N/A.
=> fix: update side navigation

packages/design/tailwind/css/components/combo-box.css, packages/design/tailwind/css/components/common.css, packages/design/tailwind/css/components/error-text.css, packages/design/tailwind/css/components/hint-text.css, packages/design/tailwind/css/components/input-checkbox.css, packages/design/tailwind/css/components/input-text.css, packages/design/tailwind/css/components/label.css, packages/design/tailwind/css/components/select.css, packages/design/tailwind/css/components/tag.css, packages/design/tailwind/css/components/text-area.css, packages/design/tailwind/css/components/tootlip.css, packages/design/tailwind/css/typography.css, packages/html/ds/src/link/link.stories.ts, packages/react/ds/src/link/link.stories.tsx, packages/react/ds/src/tag/tag.stories.tsx
Adding semantic tokens on inputs
[28297](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/28297)
=> chore: Adding semantic tokens on inputs

packages/design/tailwind/css/components/header.css
This fix will avoid title and item labels wrapping on multiple lines
=> chore: header responsiveness

apps/docs/src/components/document/resources/copy-to-clipboard-button.tsx, packages/react/ds/src/icon-button/icon-button.test.tsx, packages/react/ds/src/icon-button/icon-button.tsx
Fix icon in copy to clipboard IconButton.
Use the proper IconButton component.
=> fix: copy to clipboard icon

packages/react/ds/src/error-text/error-text.test.tsx, packages/react/ds/src/error-text/error-text.tsx, packages/react/ds/src/error-text/types.ts, packages/react/ds/src/hint-text/hint-text.test.tsx, packages/react/ds/src/hint-text/hint-text.tsx, packages/react/ds/src/hint-text/types.ts, packages/react/ds/src/index.ts, packages/react/ds/src/label/label.test.tsx, packages/react/ds/src/label/label.tsx, packages/react/ds/src/label/types.ts
Exporting Label, Error and Hint props
[28905](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/28905)
=> chore: Exporting Label, Error and Hint props

packages/design/tailwind/css/components/combo-box.css, packages/design/tailwind/css/components/footer.css, packages/design/tailwind/css/components/hint-text.css, packages/design/tailwind/css/components/input-text.css, packages/design/tailwind/css/components/label.css, packages/design/tailwind/css/components/tag.css, packages/design/tailwind/css/components/tootlip.css, packages/design/theme-builder/src/validation/schema/semantic/color-schema.ts, packages/themes/doete/tokens/light/semantic/color.json, tokens/tokens/light/semantic/color.json
Semantic tokens update
[29002](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/29002)
=> chore: Semantic tokens update

.azure/pipeline.yaml
=> ci: update prod deployment

packages/react/ds/src/forms/form-field/form-field.tsx, packages/react/ds/src/input-text/input-text.stories.tsx
=> fix: form-field missing props

packages/html/ds/src/header/header.stories.tsx, packages/html/ds/src/header/header.ts, packages/react/ds/src/header/components/header-slot.tsx, packages/react/ds/src/header/header.stories.tsx, packages/react/ds/src/header/helper.ts, packages/react/ds/src/icon/icon.tsx
Issue when click in Header Slot.
[30267](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/30267)
=> fix: Show Header Slot on click

packages/react/ds/src/progress-stepper/progress-stepper.stories.tsx, packages/react/ds/src/progress-stepper/progress-stepper.test.tsx, packages/react/ds/src/progress-stepper/progress-stepper.tsx, packages/react/ds/src/progress-stepper/types.ts
- Addition of `stepStates[]` for each progress stepper step.
N/A.
N/A.
=> fix: add progress stepper step states AB#30471

.azure/pipeline.yaml, .azure/templates/docs/close-released-tickets.yml, .azure/templates/docs/create-release-wiki-page.yml, examples/nextjs/src/app/page.tsx
Automate the wiki release note page creation
[AB#30650](https://dev.azure.com/OGCIO-Digital-Services/2aff229e-6625-4ad7-8f51-ff850dd878ec/_workitems/edit/30650)
=> ci: add wiki page creation AB#30650

.azure/visual-regression.yaml
=> ci: conditional run visual regression tests
